// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	models "ypeskov/go_hillel_9/repository/models"

	mock "github.com/stretchr/testify/mock"
)

// UserTypeRepositoryInterface is an autogenerated mock type for the UserTypeRepositoryInterface type
type UserTypeRepositoryInterface struct {
	mock.Mock
}

// GetUserTypesList provides a mock function with given fields:
func (_m *UserTypeRepositoryInterface) GetUserTypesList() ([]*models.UserType, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserTypesList")
	}

	var r0 []*models.UserType
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.UserType, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.UserType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserType)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserTypeRepositoryInterface creates a new instance of UserTypeRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserTypeRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserTypeRepositoryInterface {
	mock := &UserTypeRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
